### ISSUE TITLE
In tutorial1 

### ISSUE THREAD

**Issue by rushic24** [Santara/ML-MOOC-NPTEL#1]
plt.scatter(X_class1[:,0], X_class1[:,1],color='blue')

should be 
plt.scatter([X_class1[:,0]], [X_class1[:,1]],color='blue')

ans same for other red color

**Comment by Santara** [comment]
The syntax is okay. Please check: https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.scatter

**Comment by rushic24** [comment]
mine gives this error
"ValueError: Masked arrays must be 1-D"

that above syntax solved it

**Comment by rushic24** [comment]
also can you provide any link which shows to implement iris dataset with all 4 features ?
X = iris.data[:,:2] #Choosing only the first two input-features

ie i want to do using X=iris.data[:]
